# Generated by Django 5.0.6 on 2024-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("registration_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StickyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_note", models.CharField(max_length=30)),
            ],
        ),
    ]
