# Generated by Django 5.0.6 on 2024-06-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynotes_app', '0004_stickynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('red', 'Red')], default='yellow', max_length=20),
        ),
    ]
