# Generated by Django 5.0.6 on 2024-06-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynotes_app', '0005_stickynote_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='color',
            field=models.CharField(choices=[('#FFB3BA', 'Soft Pink'), ('#FFDFBA', 'Peach'), ('#FFFFBA', 'Light Yellow'), ('#BAFFC9', 'Light Green'), ('#BAE1FF', 'Light Blue'), ('#D3C4E3', 'Lavender')], default='#FFFFBA', max_length=20),
        ),
    ]
